/**
 * List of countries for form selects
 * Sorted alphabetically with common B2B export destinations first
 */

export interface Country {
  code: string;
  name: {
    fr: string;
    en: string;
  };
}

// Priority countries (common export destinations) - shown first
export const PRIORITY_COUNTRIES: Country[] = [
  { code: 'FR', name: { fr: 'France', en: 'France' } },
  { code: 'BE', name: { fr: 'Belgique', en: 'Belgium' } },
  { code: 'DE', name: { fr: 'Allemagne', en: 'Germany' } },
  { code: 'NL', name: { fr: 'Pays-Bas', en: 'Netherlands' } },
  { code: 'CH', name: { fr: 'Suisse', en: 'Switzerland' } },
  { code: 'IT', name: { fr: 'Italie', en: 'Italy' } },
  { code: 'ES', name: { fr: 'Espagne', en: 'Spain' } },
  { code: 'GB', name: { fr: 'Royaume-Uni', en: 'United Kingdom' } },
  { code: 'US', name: { fr: 'États-Unis', en: 'United States' } },
  { code: 'CN', name: { fr: 'Chine', en: 'China' } },
];

// All countries alphabetically
export const ALL_COUNTRIES: Country[] = [
  { code: 'AF', name: { fr: 'Afghanistan', en: 'Afghanistan' } },
  { code: 'ZA', name: { fr: 'Afrique du Sud', en: 'South Africa' } },
  { code: 'AL', name: { fr: 'Albanie', en: 'Albania' } },
  { code: 'DZ', name: { fr: 'Algérie', en: 'Algeria' } },
  { code: 'DE', name: { fr: 'Allemagne', en: 'Germany' } },
  { code: 'AD', name: { fr: 'Andorre', en: 'Andorra' } },
  { code: 'AO', name: { fr: 'Angola', en: 'Angola' } },
  { code: 'SA', name: { fr: 'Arabie Saoudite', en: 'Saudi Arabia' } },
  { code: 'AR', name: { fr: 'Argentine', en: 'Argentina' } },
  { code: 'AM', name: { fr: 'Arménie', en: 'Armenia' } },
  { code: 'AU', name: { fr: 'Australie', en: 'Australia' } },
  { code: 'AT', name: { fr: 'Autriche', en: 'Austria' } },
  { code: 'AZ', name: { fr: 'Azerbaïdjan', en: 'Azerbaijan' } },
  { code: 'BH', name: { fr: 'Bahreïn', en: 'Bahrain' } },
  { code: 'BD', name: { fr: 'Bangladesh', en: 'Bangladesh' } },
  { code: 'BE', name: { fr: 'Belgique', en: 'Belgium' } },
  { code: 'BJ', name: { fr: 'Bénin', en: 'Benin' } },
  { code: 'BY', name: { fr: 'Biélorussie', en: 'Belarus' } },
  { code: 'BO', name: { fr: 'Bolivie', en: 'Bolivia' } },
  { code: 'BA', name: { fr: 'Bosnie-Herzégovine', en: 'Bosnia and Herzegovina' } },
  { code: 'BW', name: { fr: 'Botswana', en: 'Botswana' } },
  { code: 'BR', name: { fr: 'Brésil', en: 'Brazil' } },
  { code: 'BG', name: { fr: 'Bulgarie', en: 'Bulgaria' } },
  { code: 'BF', name: { fr: 'Burkina Faso', en: 'Burkina Faso' } },
  { code: 'BI', name: { fr: 'Burundi', en: 'Burundi' } },
  { code: 'KH', name: { fr: 'Cambodge', en: 'Cambodia' } },
  { code: 'CM', name: { fr: 'Cameroun', en: 'Cameroon' } },
  { code: 'CA', name: { fr: 'Canada', en: 'Canada' } },
  { code: 'CV', name: { fr: 'Cap-Vert', en: 'Cape Verde' } },
  { code: 'CF', name: { fr: 'Centrafrique', en: 'Central African Republic' } },
  { code: 'CL', name: { fr: 'Chili', en: 'Chile' } },
  { code: 'CN', name: { fr: 'Chine', en: 'China' } },
  { code: 'CY', name: { fr: 'Chypre', en: 'Cyprus' } },
  { code: 'CO', name: { fr: 'Colombie', en: 'Colombia' } },
  { code: 'KM', name: { fr: 'Comores', en: 'Comoros' } },
  { code: 'CG', name: { fr: 'Congo', en: 'Congo' } },
  { code: 'CD', name: { fr: 'Congo (RDC)', en: 'DR Congo' } },
  { code: 'KR', name: { fr: 'Corée du Sud', en: 'South Korea' } },
  { code: 'CR', name: { fr: 'Costa Rica', en: 'Costa Rica' } },
  { code: 'CI', name: { fr: "Côte d'Ivoire", en: 'Ivory Coast' } },
  { code: 'HR', name: { fr: 'Croatie', en: 'Croatia' } },
  { code: 'CU', name: { fr: 'Cuba', en: 'Cuba' } },
  { code: 'DK', name: { fr: 'Danemark', en: 'Denmark' } },
  { code: 'DJ', name: { fr: 'Djibouti', en: 'Djibouti' } },
  { code: 'EG', name: { fr: 'Égypte', en: 'Egypt' } },
  { code: 'AE', name: { fr: 'Émirats Arabes Unis', en: 'United Arab Emirates' } },
  { code: 'EC', name: { fr: 'Équateur', en: 'Ecuador' } },
  { code: 'ER', name: { fr: 'Érythrée', en: 'Eritrea' } },
  { code: 'ES', name: { fr: 'Espagne', en: 'Spain' } },
  { code: 'EE', name: { fr: 'Estonie', en: 'Estonia' } },
  { code: 'US', name: { fr: 'États-Unis', en: 'United States' } },
  { code: 'ET', name: { fr: 'Éthiopie', en: 'Ethiopia' } },
  { code: 'FI', name: { fr: 'Finlande', en: 'Finland' } },
  { code: 'FR', name: { fr: 'France', en: 'France' } },
  { code: 'GA', name: { fr: 'Gabon', en: 'Gabon' } },
  { code: 'GM', name: { fr: 'Gambie', en: 'Gambia' } },
  { code: 'GE', name: { fr: 'Géorgie', en: 'Georgia' } },
  { code: 'GH', name: { fr: 'Ghana', en: 'Ghana' } },
  { code: 'GR', name: { fr: 'Grèce', en: 'Greece' } },
  { code: 'GT', name: { fr: 'Guatemala', en: 'Guatemala' } },
  { code: 'GN', name: { fr: 'Guinée', en: 'Guinea' } },
  { code: 'GQ', name: { fr: 'Guinée Équatoriale', en: 'Equatorial Guinea' } },
  { code: 'GW', name: { fr: 'Guinée-Bissau', en: 'Guinea-Bissau' } },
  { code: 'HT', name: { fr: 'Haïti', en: 'Haiti' } },
  { code: 'HN', name: { fr: 'Honduras', en: 'Honduras' } },
  { code: 'HK', name: { fr: 'Hong Kong', en: 'Hong Kong' } },
  { code: 'HU', name: { fr: 'Hongrie', en: 'Hungary' } },
  { code: 'IN', name: { fr: 'Inde', en: 'India' } },
  { code: 'ID', name: { fr: 'Indonésie', en: 'Indonesia' } },
  { code: 'IQ', name: { fr: 'Irak', en: 'Iraq' } },
  { code: 'IR', name: { fr: 'Iran', en: 'Iran' } },
  { code: 'IE', name: { fr: 'Irlande', en: 'Ireland' } },
  { code: 'IS', name: { fr: 'Islande', en: 'Iceland' } },
  { code: 'IL', name: { fr: 'Israël', en: 'Israel' } },
  { code: 'IT', name: { fr: 'Italie', en: 'Italy' } },
  { code: 'JM', name: { fr: 'Jamaïque', en: 'Jamaica' } },
  { code: 'JP', name: { fr: 'Japon', en: 'Japan' } },
  { code: 'JO', name: { fr: 'Jordanie', en: 'Jordan' } },
  { code: 'KZ', name: { fr: 'Kazakhstan', en: 'Kazakhstan' } },
  { code: 'KE', name: { fr: 'Kenya', en: 'Kenya' } },
  { code: 'KW', name: { fr: 'Koweït', en: 'Kuwait' } },
  { code: 'LA', name: { fr: 'Laos', en: 'Laos' } },
  { code: 'LV', name: { fr: 'Lettonie', en: 'Latvia' } },
  { code: 'LB', name: { fr: 'Liban', en: 'Lebanon' } },
  { code: 'LR', name: { fr: 'Liberia', en: 'Liberia' } },
  { code: 'LY', name: { fr: 'Libye', en: 'Libya' } },
  { code: 'LT', name: { fr: 'Lituanie', en: 'Lithuania' } },
  { code: 'LU', name: { fr: 'Luxembourg', en: 'Luxembourg' } },
  { code: 'MK', name: { fr: 'Macédoine du Nord', en: 'North Macedonia' } },
  { code: 'MG', name: { fr: 'Madagascar', en: 'Madagascar' } },
  { code: 'MY', name: { fr: 'Malaisie', en: 'Malaysia' } },
  { code: 'MW', name: { fr: 'Malawi', en: 'Malawi' } },
  { code: 'ML', name: { fr: 'Mali', en: 'Mali' } },
  { code: 'MT', name: { fr: 'Malte', en: 'Malta' } },
  { code: 'MA', name: { fr: 'Maroc', en: 'Morocco' } },
  { code: 'MU', name: { fr: 'Maurice', en: 'Mauritius' } },
  { code: 'MR', name: { fr: 'Mauritanie', en: 'Mauritania' } },
  { code: 'MX', name: { fr: 'Mexique', en: 'Mexico' } },
  { code: 'MD', name: { fr: 'Moldavie', en: 'Moldova' } },
  { code: 'MC', name: { fr: 'Monaco', en: 'Monaco' } },
  { code: 'MN', name: { fr: 'Mongolie', en: 'Mongolia' } },
  { code: 'ME', name: { fr: 'Monténégro', en: 'Montenegro' } },
  { code: 'MZ', name: { fr: 'Mozambique', en: 'Mozambique' } },
  { code: 'MM', name: { fr: 'Myanmar', en: 'Myanmar' } },
  { code: 'NA', name: { fr: 'Namibie', en: 'Namibia' } },
  { code: 'NP', name: { fr: 'Népal', en: 'Nepal' } },
  { code: 'NI', name: { fr: 'Nicaragua', en: 'Nicaragua' } },
  { code: 'NE', name: { fr: 'Niger', en: 'Niger' } },
  { code: 'NG', name: { fr: 'Nigeria', en: 'Nigeria' } },
  { code: 'NO', name: { fr: 'Norvège', en: 'Norway' } },
  { code: 'NZ', name: { fr: 'Nouvelle-Zélande', en: 'New Zealand' } },
  { code: 'OM', name: { fr: 'Oman', en: 'Oman' } },
  { code: 'UG', name: { fr: 'Ouganda', en: 'Uganda' } },
  { code: 'UZ', name: { fr: 'Ouzbékistan', en: 'Uzbekistan' } },
  { code: 'PK', name: { fr: 'Pakistan', en: 'Pakistan' } },
  { code: 'PA', name: { fr: 'Panama', en: 'Panama' } },
  { code: 'PY', name: { fr: 'Paraguay', en: 'Paraguay' } },
  { code: 'NL', name: { fr: 'Pays-Bas', en: 'Netherlands' } },
  { code: 'PE', name: { fr: 'Pérou', en: 'Peru' } },
  { code: 'PH', name: { fr: 'Philippines', en: 'Philippines' } },
  { code: 'PL', name: { fr: 'Pologne', en: 'Poland' } },
  { code: 'PT', name: { fr: 'Portugal', en: 'Portugal' } },
  { code: 'QA', name: { fr: 'Qatar', en: 'Qatar' } },
  { code: 'RO', name: { fr: 'Roumanie', en: 'Romania' } },
  { code: 'GB', name: { fr: 'Royaume-Uni', en: 'United Kingdom' } },
  { code: 'RU', name: { fr: 'Russie', en: 'Russia' } },
  { code: 'RW', name: { fr: 'Rwanda', en: 'Rwanda' } },
  { code: 'SN', name: { fr: 'Sénégal', en: 'Senegal' } },
  { code: 'RS', name: { fr: 'Serbie', en: 'Serbia' } },
  { code: 'SL', name: { fr: 'Sierra Leone', en: 'Sierra Leone' } },
  { code: 'SG', name: { fr: 'Singapour', en: 'Singapore' } },
  { code: 'SK', name: { fr: 'Slovaquie', en: 'Slovakia' } },
  { code: 'SI', name: { fr: 'Slovénie', en: 'Slovenia' } },
  { code: 'SO', name: { fr: 'Somalie', en: 'Somalia' } },
  { code: 'SD', name: { fr: 'Soudan', en: 'Sudan' } },
  { code: 'SS', name: { fr: 'Soudan du Sud', en: 'South Sudan' } },
  { code: 'LK', name: { fr: 'Sri Lanka', en: 'Sri Lanka' } },
  { code: 'SE', name: { fr: 'Suède', en: 'Sweden' } },
  { code: 'CH', name: { fr: 'Suisse', en: 'Switzerland' } },
  { code: 'SY', name: { fr: 'Syrie', en: 'Syria' } },
  { code: 'TW', name: { fr: 'Taïwan', en: 'Taiwan' } },
  { code: 'TZ', name: { fr: 'Tanzanie', en: 'Tanzania' } },
  { code: 'TD', name: { fr: 'Tchad', en: 'Chad' } },
  { code: 'CZ', name: { fr: 'Tchéquie', en: 'Czech Republic' } },
  { code: 'TH', name: { fr: 'Thaïlande', en: 'Thailand' } },
  { code: 'TG', name: { fr: 'Togo', en: 'Togo' } },
  { code: 'TN', name: { fr: 'Tunisie', en: 'Tunisia' } },
  { code: 'TR', name: { fr: 'Turquie', en: 'Turkey' } },
  { code: 'UA', name: { fr: 'Ukraine', en: 'Ukraine' } },
  { code: 'UY', name: { fr: 'Uruguay', en: 'Uruguay' } },
  { code: 'VE', name: { fr: 'Venezuela', en: 'Venezuela' } },
  { code: 'VN', name: { fr: 'Vietnam', en: 'Vietnam' } },
  { code: 'YE', name: { fr: 'Yémen', en: 'Yemen' } },
  { code: 'ZM', name: { fr: 'Zambie', en: 'Zambia' } },
  { code: 'ZW', name: { fr: 'Zimbabwe', en: 'Zimbabwe' } },
];

/**
 * Get countries for select options
 * Priority countries first, then separator, then all others
 */
export function getCountryOptions(locale: 'fr' | 'en' = 'fr') {
  const priorityCodes = new Set(PRIORITY_COUNTRIES.map(c => c.code));
  const otherCountries = ALL_COUNTRIES.filter(c => !priorityCodes.has(c.code));
  
  return [
    // Priority countries
    ...PRIORITY_COUNTRIES.map(c => ({
      value: c.code,
      label: c.name[locale],
    })),
    // Separator
    { value: '__separator__', label: '──────────', disabled: true },
    // Other countries
    ...otherCountries.map(c => ({
      value: c.code,
      label: c.name[locale],
    })),
  ];
}
